main: com.Sagacious_.KitpvpStats.Core
name: PVPPremium
version: 1.1.1
author: Sagacious_
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Vault, HolographicDisplays]
commands: 
  stats:
   aliases: [statistics]
  leaderboardrefresh:
   usage: /<command>
  moveleaderboard:
   aliases: [movelb] 
  adminreset:
   aliases: [ar]
  statsreset:
   aliases: [sr] 
  setstats:
   usage: /<command>
  removestats:
   usage: /<command>
  addstats:
   usage: /<command>
  bounty:
   usage: /<command> 